---
schema:
  procedures: {}
  tables:
    jedi_auth_roles:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - id
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
        - deferrable: 1
          expression: ''
          fields:
            - name
          match_type: ''
          name: uniq_name
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: UNIQUE
      fields:
        id:
          data_type: integer
          default_value: ~
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: id
          order: 1
          size:
            - 0
        name:
          data_type: ''
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 1
          name: name
          order: 2
          size:
            - 0
      indices: []
      name: jedi_auth_roles
      options: []
      order: 1
    jedi_auth_users:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - id
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
        - deferrable: 1
          expression: ''
          fields:
            - user
          match_type: ''
          name: uniq_user
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: UNIQUE
        - deferrable: 1
          expression: ''
          fields:
            - uuid
          match_type: ''
          name: uuid
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: UNIQUE
      fields:
        id:
          data_type: integer
          default_value: ~
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: id
          order: 1
          size:
            - 0
        info:
          data_type: ''
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: info
          order: 5
          size:
            - 0
        password:
          data_type: ''
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: password
          order: 3
          size:
            - 0
        user:
          data_type: ''
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 1
          name: user
          order: 2
          size:
            - 0
        uuid:
          data_type: ''
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 1
          name: uuid
          order: 4
          size:
            - 0
      indices: []
      name: jedi_auth_users
      options: []
      order: 2
    jedi_auth_users_roles:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - user_id
            - role_id
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
      fields:
        role_id:
          data_type: integer
          default_value: ~
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: role_id
          order: 2
          size:
            - 0
        user_id:
          data_type: integer
          default_value: ~
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: user_id
          order: 1
          size:
            - 0
      indices: []
      name: jedi_auth_users_roles
      options: []
      order: 3
  triggers: {}
  views: {}
translator:
  add_drop_table: 0
  filename: ~
  no_comments: 0
  parser_args:
    sources:
      - User
      - UsersRoles
      - Role
  parser_type: SQL::Translator::Parser::DBIx::Class
  producer_args: {}
  producer_type: SQL::Translator::Producer::YAML
  show_warnings: 0
  trace: 0
  version: 0.11018
